"""initial tables: users and tasks

Revision ID: 47cafe82095b
Revises: 
Create Date: 2026-03-17 22:55:41.128710

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '47cafe82095b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
